/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xleeji00;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author leehu
 */
public class Calculator extends javax.swing.JFrame implements KeyListener{
    String expression = "0";
    String operation = "";
    double firstnumber;
    double secondnumber;
    double result;
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        setFocusable(true);
        addKeyListener(this);
        
        initComponents();    
        SinusButton.setVisible(false);
        CosinusButton.setVisible(false);
        ExponentialButton.setVisible(false);
        LogarithmButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    DefaultListModel dlm = new DefaultListModel();
    List<memoryCollection> list = new ArrayList<>();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NotationButtonGroup = new javax.swing.ButtonGroup();
        NoticeFrame = new javax.swing.JFrame();
        FormulaFields = new javax.swing.JLabel();
        InputAndOutputFields = new javax.swing.JLabel();
        HexRadioButton = new javax.swing.JRadioButton();
        DecRadioButton = new javax.swing.JRadioButton();
        OctRadioButton = new javax.swing.JRadioButton();
        BinRadioButton = new javax.swing.JRadioButton();
        ZeroButton = new javax.swing.JButton();
        DecimalMarkButton = new javax.swing.JButton();
        EqualSignButton = new javax.swing.JButton();
        EButton = new javax.swing.JButton();
        FButton = new javax.swing.JButton();
        OneButton = new javax.swing.JButton();
        TwoButton = new javax.swing.JButton();
        ThreeButton = new javax.swing.JButton();
        AdditionButton = new javax.swing.JButton();
        CButton = new javax.swing.JButton();
        DButton = new javax.swing.JButton();
        FourButton = new javax.swing.JButton();
        FiveButton = new javax.swing.JButton();
        SixButton = new javax.swing.JButton();
        SubtractionButton = new javax.swing.JButton();
        AButton = new javax.swing.JButton();
        BButton = new javax.swing.JButton();
        SevenButton = new javax.swing.JButton();
        EightButton = new javax.swing.JButton();
        NineButton = new javax.swing.JButton();
        MultiplicationButton = new javax.swing.JButton();
        ModuloButton = new javax.swing.JButton();
        ClearEntryButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        DivisionButton = new javax.swing.JButton();
        SinusButton = new javax.swing.JButton();
        CosinusButton = new javax.swing.JButton();
        ExponentialButton = new javax.swing.JButton();
        LogarithmButton = new javax.swing.JButton();
        AdvancedToggleButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MemoryList = new javax.swing.JList<>();
        GetButton = new javax.swing.JButton();

        javax.swing.GroupLayout NoticeFrameLayout = new javax.swing.GroupLayout(NoticeFrame.getContentPane());
        NoticeFrame.getContentPane().setLayout(NoticeFrameLayout);
        NoticeFrameLayout.setHorizontalGroup(
            NoticeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        NoticeFrameLayout.setVerticalGroup(
            NoticeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FormulaFields.setForeground(new java.awt.Color(102, 102, 102));
        FormulaFields.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        InputAndOutputFields.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        InputAndOutputFields.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InputAndOutputFields.setText("0");

        NotationButtonGroup.add(HexRadioButton);
        HexRadioButton.setText("HEX");
        HexRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HexRadioButtonActionPerformed(evt);
            }
        });

        NotationButtonGroup.add(DecRadioButton);
        DecRadioButton.setSelected(true);
        DecRadioButton.setText("DEC");
        DecRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecRadioButtonActionPerformed(evt);
            }
        });

        NotationButtonGroup.add(OctRadioButton);
        OctRadioButton.setText("OCT");
        OctRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OctRadioButtonActionPerformed(evt);
            }
        });

        NotationButtonGroup.add(BinRadioButton);
        BinRadioButton.setText("BIN");
        BinRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinRadioButtonActionPerformed(evt);
            }
        });

        ZeroButton.setText("0");
        ZeroButton.setFocusable(false);
        ZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroButtonActionPerformed(evt);
            }
        });

        DecimalMarkButton.setText(".");
        DecimalMarkButton.setFocusable(false);
        DecimalMarkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecimalMarkButtonActionPerformed(evt);
            }
        });

        EqualSignButton.setText("=");
        EqualSignButton.setFocusable(false);
        EqualSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualSignButtonActionPerformed(evt);
            }
        });

        EButton.setText("E");
        EButton.setEnabled(false);
        EButton.setFocusable(false);
        EButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EButtonActionPerformed(evt);
            }
        });

        FButton.setText("F");
        FButton.setEnabled(false);
        FButton.setFocusable(false);
        FButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FButtonActionPerformed(evt);
            }
        });

        OneButton.setText("1");
        OneButton.setFocusable(false);
        OneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneButtonActionPerformed(evt);
            }
        });

        TwoButton.setText("2");
        TwoButton.setFocusable(false);
        TwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoButtonActionPerformed(evt);
            }
        });

        ThreeButton.setText("3");
        ThreeButton.setFocusable(false);
        ThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeButtonActionPerformed(evt);
            }
        });

        AdditionButton.setText("+");
        AdditionButton.setFocusable(false);
        AdditionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditionButtonActionPerformed(evt);
            }
        });

        CButton.setText("C");
        CButton.setEnabled(false);
        CButton.setFocusable(false);
        CButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CButtonActionPerformed(evt);
            }
        });

        DButton.setText("D");
        DButton.setEnabled(false);
        DButton.setFocusable(false);
        DButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DButtonActionPerformed(evt);
            }
        });

        FourButton.setText("4");
        FourButton.setFocusable(false);
        FourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourButtonActionPerformed(evt);
            }
        });

        FiveButton.setText("5");
        FiveButton.setFocusable(false);
        FiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveButtonActionPerformed(evt);
            }
        });

        SixButton.setText("6");
        SixButton.setFocusable(false);
        SixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixButtonActionPerformed(evt);
            }
        });

        SubtractionButton.setText("-");
        SubtractionButton.setFocusable(false);
        SubtractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractionButtonActionPerformed(evt);
            }
        });

        AButton.setText("A");
        AButton.setEnabled(false);
        AButton.setFocusable(false);
        AButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AButtonActionPerformed(evt);
            }
        });

        BButton.setText("B");
        BButton.setEnabled(false);
        BButton.setFocusable(false);
        BButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BButtonActionPerformed(evt);
            }
        });

        SevenButton.setText("7");
        SevenButton.setFocusable(false);
        SevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenButtonActionPerformed(evt);
            }
        });

        EightButton.setText("8");
        EightButton.setFocusable(false);
        EightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightButtonActionPerformed(evt);
            }
        });

        NineButton.setText("9");
        NineButton.setFocusable(false);
        NineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineButtonActionPerformed(evt);
            }
        });

        MultiplicationButton.setText("X");
        MultiplicationButton.setFocusable(false);
        MultiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicationButtonActionPerformed(evt);
            }
        });

        ModuloButton.setText("Mod");
        ModuloButton.setFocusable(false);
        ModuloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModuloButtonActionPerformed(evt);
            }
        });

        ClearEntryButton.setText("CE");
        ClearEntryButton.setFocusable(false);
        ClearEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearEntryButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("C");
        ClearButton.setFocusable(false);
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Del");
        DeleteButton.setFocusable(false);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        DivisionButton.setText("/");
        DivisionButton.setFocusable(false);
        DivisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionButtonActionPerformed(evt);
            }
        });

        SinusButton.setText("sin");
        SinusButton.setFocusable(false);
        SinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinusButtonActionPerformed(evt);
            }
        });

        CosinusButton.setText("cos");
        CosinusButton.setFocusable(false);
        CosinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosinusButtonActionPerformed(evt);
            }
        });

        ExponentialButton.setText("exp");
        ExponentialButton.setFocusable(false);
        ExponentialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExponentialButtonActionPerformed(evt);
            }
        });

        LogarithmButton.setText("log");
        LogarithmButton.setFocusable(false);
        LogarithmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogarithmButtonActionPerformed(evt);
            }
        });

        AdvancedToggleButton.setText("Adv");
        AdvancedToggleButton.setFocusable(false);
        AdvancedToggleButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        AdvancedToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvancedToggleButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("굴림", 0, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>  HEX, OCT and  BIN show and compute <br> only digits above the Decimal points </html>");

        MemoryList.setBackground(new java.awt.Color(240, 240, 240));
        MemoryList.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        MemoryList.setToolTipText("");
        MemoryList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MemoryList.setFocusable(false);
        jScrollPane1.setViewportView(MemoryList);

        GetButton.setText("GET");
        GetButton.setFocusable(false);
        GetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DecimalMarkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EqualSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SubtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AdditionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(FormulaFields, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputAndOutputFields, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(AButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(MultiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(AdvancedToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ModuloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(HexRadioButton)
                                        .addComponent(DecRadioButton))
                                    .addGap(2, 2, 2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(OctRadioButton)
                                        .addComponent(BinRadioButton))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(SinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CosinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ExponentialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LogarithmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ClearEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DivisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(GetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FormulaFields, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputAndOutputFields)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HexRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DecRadioButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CosinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ExponentialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LogarithmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OctRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BinRadioButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModuloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DivisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdvancedToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MultiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdditionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DecimalMarkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EqualSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(GetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Input 0
     * @param evt 
     */
    private void ZeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += ZeroButton.getText();
        InputAndOutputFields.setText(expression);
    }//GEN-LAST:event_ZeroButtonActionPerformed

    /**
     * Input 1
     * @param evt 
     */
    private void OneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += OneButton.getText();
        InputAndOutputFields.setText(expression);
    }//GEN-LAST:event_OneButtonActionPerformed

    /**
     * Input 2
     * @param evt 
     */
    private void TwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += TwoButton.getText();
        InputAndOutputFields.setText(expression);
    }//GEN-LAST:event_TwoButtonActionPerformed

    /**
     * Input 3
     * @param evt 
     */
    private void ThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += ThreeButton.getText();
        InputAndOutputFields.setText(expression);

    }//GEN-LAST:event_ThreeButtonActionPerformed

    /**
     * Input 4
     * @param evt 
     */
    private void FourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += FourButton.getText();
        InputAndOutputFields.setText(expression);

    }//GEN-LAST:event_FourButtonActionPerformed

    /**
     * Input 5
     * @param evt 
     */
    private void FiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += FiveButton.getText();
        InputAndOutputFields.setText(expression);

    }//GEN-LAST:event_FiveButtonActionPerformed

    /**
     * Input 6
     * @param evt 
     */
    private void SixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += SixButton.getText();
        InputAndOutputFields.setText(expression);

    }//GEN-LAST:event_SixButtonActionPerformed

    /**
     * Input 7
     * @param evt 
     */
    private void SevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += SevenButton.getText();
        InputAndOutputFields.setText(expression);
    }//GEN-LAST:event_SevenButtonActionPerformed

    /**
     * Input 8
     * @param evt 
     */
    private void EightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += EightButton.getText();
        InputAndOutputFields.setText(expression);
    }//GEN-LAST:event_EightButtonActionPerformed

    /**
     * Input 9
     * @param evt 
     */
    private void NineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += NineButton.getText();
        InputAndOutputFields.setText(expression);
    }//GEN-LAST:event_NineButtonActionPerformed

    /**
     * Input A
     * @param evt 
     */
    private void AButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += AButton.getText();
        InputAndOutputFields.setText(expression);
    }//GEN-LAST:event_AButtonActionPerformed

    /**
     * Input B
     * @param evt 
     */
    private void BButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += BButton.getText();
        InputAndOutputFields.setText(expression);
    }//GEN-LAST:event_BButtonActionPerformed

    /**
     * Input C
     * @param evt 
     */
    private void CButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += CButton.getText();
        InputAndOutputFields.setText(expression);
    }//GEN-LAST:event_CButtonActionPerformed

    /**
     * Input D
     * @param evt 
     */
    private void DButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += DButton.getText();
        InputAndOutputFields.setText(expression);
    }//GEN-LAST:event_DButtonActionPerformed

    /**
     * Input E
     * @param evt 
     */
    private void EButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += EButton.getText();
         InputAndOutputFields.setText(expression);
    }//GEN-LAST:event_EButtonActionPerformed

    /**
     * Input F
     * @param evt 
     */
    private void FButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("0")){
            expression = "";
        }
        expression += FButton.getText();
        InputAndOutputFields.setText(expression);
    }//GEN-LAST:event_FButtonActionPerformed

    /**
     * Input +
     * @param evt 
     */
    private void AdditionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditionButtonActionPerformed
        // TODO add your handling code here:   
        if(operation !="="&&expression.equals("")){
            JOptionPane.showMessageDialog(NoticeFrame, "Input Number");
            return;
        }
        else {
            firstnumber = update();
            FormulaFields.setText(EraseMark(firstnumber) + " " + AdditionButton.getText());
            expression = "";
            operation = "+";
        }
    }//GEN-LAST:event_AdditionButtonActionPerformed

    /**
     * Input -
     * @param evt 
     */
    private void SubtractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractionButtonActionPerformed
        // TODO add your handling code here:
        if(operation !="="&&expression.equals("")){
            JOptionPane.showMessageDialog(NoticeFrame, "Input Number");
            return;
        }
        else{
            firstnumber = update();
            FormulaFields.setText(EraseMark(firstnumber) + " " +  SubtractionButton.getText());
            expression = "";
            operation = "-";
        }
    }//GEN-LAST:event_SubtractionButtonActionPerformed

    /**
     * Input *
     * @param evt 
     */
    private void MultiplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicationButtonActionPerformed
        // TODO add your handling code here:
        if(operation !="="&&expression.equals("")){
            JOptionPane.showMessageDialog(NoticeFrame, "Input Number");
            return;
        }
        else {        
            firstnumber = update();
            FormulaFields.setText(EraseMark(firstnumber) + " " +  MultiplicationButton.getText());
            expression = "";
            operation = "*";
        }
    }//GEN-LAST:event_MultiplicationButtonActionPerformed

    /**
     * Input /
     * @param evt 
     */
    private void DivisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionButtonActionPerformed
        // TODO add your handling code here:
        if(operation !="="&&expression.equals("")){
            JOptionPane.showMessageDialog(NoticeFrame, "Input Number");
            return;
        }
        else{
            firstnumber = update();
            FormulaFields.setText(EraseMark(firstnumber) +" " +  DivisionButton.getText());
            expression = "";
            operation = "/";
        }
    }//GEN-LAST:event_DivisionButtonActionPerformed

    /**
     * Change number to show
     * @param evt 
     */
    private double update(){
        double number;
        
        if(DecRadioButton.isSelected()){
             number = Double.parseDouble(InputAndOutputFields.getText());
        }
        else{
            number = compute();
        }
        return number;
    }
    
    /**
     * Compute different number base
     * @param evt 
     */
    private double compute(){
        String str = InputAndOutputFields.getText();
        double index=1;
        double number = 0;
        
        
        for(int i=str.length()-1; i>=0; i--){
            if(str.charAt(i) - 48  == 17){
                number += 10*index;
            }
            else if(str.charAt(i) - 48  == 18){
                number += 11*index;
            }
            else if(str.charAt(i) - 48  == 19){
                number += 12*index;
            }
            else if(str.charAt(i) - 48  == 20){
                number += 13*index;
            }
            else if(str.charAt(i) - 48  == 21){
                number += 14*index;
            }
            else if(str.charAt(i) - 48  == 22){
                number += 15*index;
            }
            else{
                number += (str.charAt(i) - 48) * index;
            }
            
            if(HexRadioButton.isSelected()){
                index *= 16;
            }
            else if(DecRadioButton.isSelected()){
                index *= 10;
            }
            else if(OctRadioButton.isSelected()){
                index *= 8;
            }
            else{
                index *= 2;
            }
        }
        
        return number;
    }

    /**
     * Erase Decimal point in double
     * @param evt 
     */
    private String EraseMark(double number){
        number = Math.round(number*10000000000d)/10000000000d;
        
        if(HexRadioButton.isSelected()){
            return notationCompute((int)number, 16);
        }
        else if(DecRadioButton.isSelected()){
            if(number == (long) number)
                return String.format("%d",(long)number);
            else{
                return String.format("%s",number);
            }
        }
        else if(OctRadioButton.isSelected()){
            return notationCompute((int)number, 8);
        }
        else{
            return notationCompute((int)number, 2);
        }
    }
    
     /**
     * Compute different number base notation
     * @param evt 
     */
    private String notationCompute(int number, int notation){
        String hex="";
        int modnum;
        if(number==0){
            hex="0";
        }
        
        while(number>0){
            modnum = number % notation; 
            if(modnum==10){
                hex = "A"+hex;
            }
            else if(modnum==11){
                hex = "B"+hex;
            }
            else if(modnum==12){
                hex = "C"+hex;
            }
            else if(modnum==13){
                hex = "D"+hex;
            }
            else if(modnum==14){
                hex = "E"+hex;
            }
            else if(modnum==15){
                hex = "F"+hex;
            }
            else{
                hex = modnum + hex;
            }
            number = number/notation;
        }
        return hex;
    }
    
    /**
     * Calculate formula
     * @param evt 
     */
    private void EqualSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualSignButtonActionPerformed
        // TODO add your handling code here:
        
        if(expression.equals("")){
            JOptionPane.showMessageDialog(NoticeFrame, "Input Number");
            return;
        }
        else if(operation.equals("")){
            JOptionPane.showMessageDialog(NoticeFrame, "Input operation");
            return;
        }
        secondnumber = update();
        
        FormulaFields.setText(EraseMark(firstnumber) + " " + operation + " " + EraseMark(secondnumber) + " " + "=");
        if(operation.equals("+")){
            result = firstnumber + secondnumber;
        }
        else if(operation.equals("-")){
            result = firstnumber - secondnumber;
        }
        else if(operation.equals("*")){
            result = firstnumber * secondnumber;
        }
        else if(operation.equals("/")){
            result = firstnumber / secondnumber;
        }
        else if(operation.equals("mod")){
            result = firstnumber % secondnumber;
        }
        
        InputAndOutputFields.setText(EraseMark(result));
        firstnumber = update();
        
        InsertMemory();
        
        secondnumber = 0;
        expression = "";
        operation = "=";
    }//GEN-LAST:event_EqualSignButtonActionPerformed

    /**
     * memory storing the result of the last computation.
     */
    private void InsertMemory(){
        memoryCollection memory = new memoryCollection(InputAndOutputFields.getText(), FormulaFields.getText());
        list.add(memory);
        
        dlm.addElement(EraseMark(result));
        MemoryList.setModel(dlm);
    }
    
    /**
     * Clear formula
     * @param evt 
     */
    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        expression = "0";
        operation = "";
        firstnumber = 0;
        secondnumber = 0;
        result = 0;
        InputAndOutputFields.setText("0");
        FormulaFields.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * Clear entry
     * @param evt 
     */
    private void ClearEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearEntryButtonActionPerformed
        // TODO add your handling code here:
        if(expression==""||expression=="0"){
            ClearButtonActionPerformed(evt);
        }
        expression = "0";
        InputAndOutputFields.setText("0");
    }//GEN-LAST:event_ClearEntryButtonActionPerformed

    /**
     * Delete one digit
     * @param evt 
     */
    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        
        if(expression.length() < 2){
            expression = "0";
            InputAndOutputFields.setText("0");
        }
        else{
            expression = expression.substring(0, expression.length()-1); 
            InputAndOutputFields.setText(expression);
        }
        
    }//GEN-LAST:event_DeleteButtonActionPerformed

    /**
     * Input .
     * @param evt 
     */
    private void DecimalMarkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecimalMarkButtonActionPerformed
        // TODO add your handling code here:
        if(expression.equals("")){
            expression = "0";
        }
        expression += DecimalMarkButton.getText();
        InputAndOutputFields.setText(expression);
    }//GEN-LAST:event_DecimalMarkButtonActionPerformed

    /**
     * Input mod
     * @param evt 
     */
    private void ModuloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModuloButtonActionPerformed
        // TODO add your handling code here:
        if(operation !="="&&expression.equals("")){
            JOptionPane.showMessageDialog(NoticeFrame, "Input Number");
            return;
        }
        else { 
            firstnumber = update();
            FormulaFields.setText(EraseMark(firstnumber) + " " +  ModuloButton.getText());
            expression = "";
            operation = "mod";        
        }
    }//GEN-LAST:event_ModuloButtonActionPerformed

    /**
     * Make radio button group
     * @param evt 
     */
    private void init(){
        NotationButtonGroup.add(HexRadioButton);
        NotationButtonGroup.add(DecRadioButton);
        NotationButtonGroup.add(OctRadioButton);
        NotationButtonGroup.add(BinRadioButton);
    }
    
    /**
     * Change number base to Dec
     * @param evt 
     */
    private void DecRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecRadioButtonActionPerformed
        // TODO add your handling code here:
        
        TwoButton.setEnabled(true);
        ThreeButton.setEnabled(true);
        FourButton.setEnabled(true);
        FiveButton.setEnabled(true);
        SixButton.setEnabled(true);
        SevenButton.setEnabled(true);
        EightButton.setEnabled(true);
        NineButton.setEnabled(true);
        DecimalMarkButton.setEnabled(true);
        AdvancedToggleButton.setEnabled(true);
        SinusButton.setEnabled(true);
        CosinusButton.setEnabled(true);
        ExponentialButton.setEnabled(true);
        LogarithmButton.setEnabled(true);
        
        AButton.setEnabled(false);
        BButton.setEnabled(false);
        CButton.setEnabled(false);
        DButton.setEnabled(false);
        EButton.setEnabled(false);
        FButton.setEnabled(false);
        
        ClearButtonActionPerformed(evt);
        dlm.removeAllElements();
    }//GEN-LAST:event_DecRadioButtonActionPerformed

     /**
     * Change number base to Hex
     * @param evt 
     */
    private void HexRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HexRadioButtonActionPerformed
        // TODO add your handling code here:
        TwoButton.setEnabled(true);
        ThreeButton.setEnabled(true);
        FourButton.setEnabled(true);
        FiveButton.setEnabled(true);
        SixButton.setEnabled(true);
        SevenButton.setEnabled(true);
        EightButton.setEnabled(true);
        NineButton.setEnabled(true);
        AButton.setEnabled(true);
        BButton.setEnabled(true);
        CButton.setEnabled(true);
        DButton.setEnabled(true);
        EButton.setEnabled(true);
        FButton.setEnabled(true);
        
        DecimalMarkButton.setEnabled(false);
        AdvancedToggleButton.setSelected(false);
        AdvancedToggleButton.setEnabled(false);
        SinusButton.setVisible(false);
        CosinusButton.setVisible(false);
        ExponentialButton.setVisible(false);
        LogarithmButton.setVisible(false);
        
        ClearButtonActionPerformed(evt);
        dlm.removeAllElements();
    }//GEN-LAST:event_HexRadioButtonActionPerformed

     /**
     * Change number base to Oct
     * @param evt 
     */
    private void OctRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OctRadioButtonActionPerformed
        // TODO add your handling code here:
        TwoButton.setEnabled(true);
        ThreeButton.setEnabled(true);
        FourButton.setEnabled(true);
        FiveButton.setEnabled(true);
        SixButton.setEnabled(true);
        SevenButton.setEnabled(true);
        
        EightButton.setEnabled(false);
        NineButton.setEnabled(false);
        AButton.setEnabled(false);
        BButton.setEnabled(false);
        CButton.setEnabled(false);
        DButton.setEnabled(false);
        EButton.setEnabled(false);
        FButton.setEnabled(false);
        DecimalMarkButton.setEnabled(false);
        AdvancedToggleButton.setSelected(false);
        AdvancedToggleButton.setEnabled(false);
        SinusButton.setVisible(false);
        CosinusButton.setVisible(false);
        ExponentialButton.setVisible(false);
        LogarithmButton.setVisible(false);
        
        ClearButtonActionPerformed(evt);
        dlm.removeAllElements();
    }//GEN-LAST:event_OctRadioButtonActionPerformed

     /**
     * Change number base to Bin
     * @param evt 
     */
    private void BinRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinRadioButtonActionPerformed
        // TODO add your handling code here:
        TwoButton.setEnabled(false);
        ThreeButton.setEnabled(false);
        FourButton.setEnabled(false);
        FiveButton.setEnabled(false);
        SixButton.setEnabled(false);
        SevenButton.setEnabled(false);
        EightButton.setEnabled(false);
        NineButton.setEnabled(false);
        
        AButton.setEnabled(false);
        BButton.setEnabled(false);
        CButton.setEnabled(false);
        DButton.setEnabled(false);
        EButton.setEnabled(false);
        FButton.setEnabled(false);
        DecimalMarkButton.setEnabled(false);
        AdvancedToggleButton.setSelected(false);
        AdvancedToggleButton.setEnabled(false);
        SinusButton.setVisible(false);
        CosinusButton.setVisible(false);
        ExponentialButton.setVisible(false);
        LogarithmButton.setVisible(false);
        
        ClearButtonActionPerformed(evt);
        dlm.removeAllElements();
    }//GEN-LAST:event_BinRadioButtonActionPerformed

    
     /**
     * Show sin, cos, exp, log buttons
     * @param evt 
     */
    private void AdvancedToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvancedToggleButtonActionPerformed
        // TODO add your handling code here:
        if(AdvancedToggleButton.isSelected()){
            SinusButton.setVisible(true);
            CosinusButton.setVisible(true);
            ExponentialButton.setVisible(true);
            LogarithmButton.setVisible(true);
        }
        else{
            SinusButton.setVisible(false);
            CosinusButton.setVisible(false);
            ExponentialButton.setVisible(false);
            LogarithmButton.setVisible(false);
        }
    }//GEN-LAST:event_AdvancedToggleButtonActionPerformed

     /**
     * input sin
     * @param evt 
     */
    private void SinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinusButtonActionPerformed
        // TODO add your handling code here:
        if(operation !="="&&expression.equals("")){
            JOptionPane.showMessageDialog(NoticeFrame, "Input Number");
            return;
        }
        else{
            firstnumber = update();
            FormulaFields.setText(SinusButton.getText() + "( " + EraseMark(firstnumber) + " )");
            result = Math.sin(Math.toRadians(firstnumber));
            InputAndOutputFields.setText(EraseMark(result));
            operation="=";
            expression = "";
            InsertMemory();
        }
    }//GEN-LAST:event_SinusButtonActionPerformed

    /**
     * input cos
     * @param evt 
     */
    private void CosinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosinusButtonActionPerformed
        // TODO add your handling code here:
        if(operation !="="&&expression.equals("")){
            JOptionPane.showMessageDialog(NoticeFrame, "Input Number");
            return;
        }
        else{
            firstnumber = update();
            FormulaFields.setText(CosinusButton.getText() + "( " + EraseMark(firstnumber) + " )");
            result = Math.cos(Math.toRadians(firstnumber));
            InputAndOutputFields.setText(EraseMark(result));
            operation="=";
            expression = "";
            InsertMemory();
        }
    }//GEN-LAST:event_CosinusButtonActionPerformed

    /**
     * input exp
     * @param evt 
     */
    private void ExponentialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExponentialButtonActionPerformed
        // TODO add your handling code here:
        if(operation !="="&&expression.equals("")){
            JOptionPane.showMessageDialog(NoticeFrame, "Input Number");
            return;
        }
        else{
            firstnumber = update();
            FormulaFields.setText("10^" + "( " + EraseMark(firstnumber) + " )");
            result = Math.pow(10, firstnumber);
            InputAndOutputFields.setText(EraseMark(result));
            operation="=";
            expression = "";
            InsertMemory();
        }
    }//GEN-LAST:event_ExponentialButtonActionPerformed

    /**
     * input log
     * @param evt 
     */
    private void LogarithmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogarithmButtonActionPerformed
        // TODO add your handling code here:
        if(operation !="="&&expression.equals("")){
            JOptionPane.showMessageDialog(NoticeFrame, "Input Number");
            return;
        }
        else{
            firstnumber = update();
            FormulaFields.setText(LogarithmButton.getText() + " ₂ ( " + EraseMark(firstnumber) + " )");
            result = Math.log(firstnumber)/Math.log(2);  
            InputAndOutputFields.setText(EraseMark(result));
            operation="=";
            expression = "";
            InsertMemory();
        }
    }//GEN-LAST:event_LogarithmButtonActionPerformed

    /**
     * use value in the memory
     * 
     * @param evt 
     */
    private void GetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetButtonActionPerformed
        // TODO add your handling code here:
        
        if(MemoryList.getModel().getSize() == 0){
            JOptionPane.showMessageDialog(NoticeFrame, "Fill Memory");
        }
        else if(MemoryList.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(NoticeFrame, "Select Memory");
        }
        else{
            InputAndOutputFields.setText(MemoryList.getSelectedValue());
            for(memoryCollection x : list){
                if(x.result.equals(MemoryList.getSelectedValue())){
                    FormulaFields.setText(x.formula);
                }
            }
        }
    }//GEN-LAST:event_GetButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Calculator frame = new Calculator();
                frame.init();
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AButton;
    private javax.swing.JButton AdditionButton;
    private javax.swing.JToggleButton AdvancedToggleButton;
    private javax.swing.JButton BButton;
    private javax.swing.JRadioButton BinRadioButton;
    private javax.swing.JButton CButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ClearEntryButton;
    private javax.swing.JButton CosinusButton;
    private javax.swing.JButton DButton;
    private javax.swing.JRadioButton DecRadioButton;
    private javax.swing.JButton DecimalMarkButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DivisionButton;
    private javax.swing.JButton EButton;
    private javax.swing.JButton EightButton;
    private javax.swing.JButton EqualSignButton;
    private javax.swing.JButton ExponentialButton;
    private javax.swing.JButton FButton;
    private javax.swing.JButton FiveButton;
    private javax.swing.JLabel FormulaFields;
    private javax.swing.JButton FourButton;
    private javax.swing.JButton GetButton;
    private javax.swing.JRadioButton HexRadioButton;
    private javax.swing.JLabel InputAndOutputFields;
    private javax.swing.JButton LogarithmButton;
    private javax.swing.JList<String> MemoryList;
    private javax.swing.JButton ModuloButton;
    private javax.swing.JButton MultiplicationButton;
    private javax.swing.JButton NineButton;
    private javax.swing.ButtonGroup NotationButtonGroup;
    private javax.swing.JFrame NoticeFrame;
    private javax.swing.JRadioButton OctRadioButton;
    private javax.swing.JButton OneButton;
    private javax.swing.JButton SevenButton;
    private javax.swing.JButton SinusButton;
    private javax.swing.JButton SixButton;
    private javax.swing.JButton SubtractionButton;
    private javax.swing.JButton ThreeButton;
    private javax.swing.JButton TwoButton;
    private javax.swing.JButton ZeroButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        
    }

    /**
     * Key press function
     * @param evt 
     */
    @Override
    public void keyPressed(KeyEvent e) {
        
        int keyCode = e.getKeyCode();
        
        if(keyCode == KeyEvent.VK_0){
            ZeroButton.doClick();
        }
        if(keyCode == KeyEvent.VK_1){
            OneButton.doClick();
        }
        if(keyCode == KeyEvent.VK_2){
            TwoButton.doClick();
        }
        if(keyCode == KeyEvent.VK_3){
            ThreeButton.doClick();
        }
        if(keyCode == KeyEvent.VK_4){
            FourButton.doClick();
        }
        if(keyCode == KeyEvent.VK_5){
            FiveButton.doClick();
        }
        if(keyCode == KeyEvent.VK_6){
            SixButton.doClick();
        }
        if(keyCode == KeyEvent.VK_7){
            SevenButton.doClick();
        }
        if(keyCode == KeyEvent.VK_8){
            EightButton.doClick();
        }
        if(keyCode == KeyEvent.VK_9){
            NineButton.doClick();
        }
        if(keyCode == KeyEvent.VK_A){
            AButton.doClick();
        }
        if(keyCode == KeyEvent.VK_B){
            BButton.doClick();
        }
        if(keyCode == KeyEvent.VK_C){
            CButton.doClick();
        }
        if(keyCode == KeyEvent.VK_D){
            DButton.doClick();
        }
        if(keyCode == KeyEvent.VK_E){
            EButton.doClick();
        }
        if(keyCode == KeyEvent.VK_F){
            FButton.doClick();
        }
        
    }

    @Override
    public void keyReleased(KeyEvent e) {
        
    }
}
